version: '2'
services:
    vm: 
      privileged: true
      image: vm:latest
      build:
        context: ./
        dockerfile: Dockerfile
      ports:
        - 6080:80
        - 5900:5900
      volumes:
        - avd:/root/.android/avd
volumes:
  avd: